texts = {
    'en': {
        'welcome': 'Welcome back to dear Diary bot! Choose a section:',
        'choose_language': 'Choose your language / Выберите ваш язык',
        'task_list': '<b>Task List</b>\n\n<i>send the task description:</i>',
        'task_added': 'Task added to the list!',
        'diary': '<b>Diary</b>\n\n<i>describe your day</i>',
        'diary_entries': '<b>Diary Entries</b>:',
        'reading_list': '<b>Reading List</b>\n\n<i>send the name of a book:</i>',
        'calendar': '<b>Calendar</b>\n\n<i>this feature is under development</i>',
        'mood_journal': '<b>Mood Journal</b>\n\n<i>how are you feeling today?</i>',
        'authorize': '<b>Please authorize</b>\n\n<i>send your login details in the format: <code>username password</code></i>',
        'authorize_error': 'Incorrect format. Please send your login details in the format: <code>username password</code></i>',
        'authorization_success': 'Authorization successful! Welcome to your personal diary bot!',
        'authorization_failed': 'Account not found. Please try again or register using /signup.',
        'signup_prompt': 'You are not registered. Please use /signup to create an account.',
        'signup': '<b>Sign Up</b>\n\n<i>send your registration details in the format: <code>username password email</code></i>',
        'signup_error': 'Incorrect format. Please send your registration details in the format: <code>username password email</code>',
        'user_exists': 'User already exists.',
        'registration_success': 'Account successfully created!',
        'task_description': 'Please enter the task description:',
        'task_deadline': 'Please enter the task deadline (YYYY-MM-DD):',
        'task_status_updated': 'Task status updated!',
    },
    'ru': {
        'welcome': 'Добро пожаловать в dear Diary bot! Выберите раздел:',
        'choose_language': 'Choose your language / Выберите ваш язык',
        'task_list': '<b>Список задач</b>\n\n<i>отправьте описание задачи:</i>',
        'task_added': 'Задача добавлена в список!',
        'diary': '<b>Дневник</b>\n\n<i>опишите свой день</i>',
        'diary_entries': '<b>Записи дневника</b>:',
        'reading_list': '<b>Список чтения</b>\n\n<i>отправьте название книги:</i>',
        'calendar': '<b>Календарь</b>\n\n<i>эта функция в разработке</i>',
        'mood_journal': '<b>Журнал настроения</b>\n\n<i>как вы сегодня себя чувствуете?</i>',
        'authorize': '<b>Пожалуйста, авторизуйтесь</b>\n\n<i>Отправьте свои данные для входа в формате: <code>username password</code></i>',
        'authorize_error': 'Неправильный формат. Пожалуйста, отправьте свои данные для входа в формате: <code>username password</code></i>',
        'authorization_success': 'Авторизация успешна! Добро пожаловать в ваш личный дневник-бот!',
        'authorization_failed': 'Аккаунт не найден. Пожалуйста, попробуйте еще раз или зарегистрируйтесь с помощью /signup.',
        'signup_prompt': 'Вы не зарегистрированы. Пожалуйста, используйте /signup для создания аккаунта.',
        'signup': '<b>Регистрация</b>\n\n<i>отправьте свои регистрационные данные в формате: <code>username password email</code></i>',
        'signup_error': 'Неправильный формат. Пожалуйста, отправьте свои регистрационные данные в формате: <code>username password email</code>',
        'user_exists': 'Пользователь уже существует.',
        'registration_success': 'Аккаунт успешно создан!',
        'task_description': 'Пожалуйста, введите описание задачи:',
        'task_deadline': 'Пожалуйста, введите срок выполнения задачи (ГГГГ-ММ-ДД):',
        'task_status_updated': 'Статус задачи обновлен!',
    }
}
